apiVersion: v1
kind: Service
metadata:
  name: {{ include "ms-rndx-wallet.fullname" . }}
  labels:
    {{- include "ms-rndx-wallet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: https
      protocol: TCP
      name: https

  selector:
    {{- include "ms-rndx-wallet.selectorLabels" . | nindent 4 }}
